### PR TITLE
build VizDoom locally

### PR DESCRIPTION
**Pull request by findmyway**
- [x] Add wrapper file and cmakefile
- [x] Add build.jl to download & build [VizDoom](https://github.com/mwydmuch/ViZDoom)
- [x] Add CI & Test
- [x] Update readme

### CODE REVIEW

**Comment by findmyway** [comment]
Hi @jbrea ,

I've just updated this package.

Now we can add more helper functions in the `deps/lib_julia/ViZDoomJuliaModule.cpp` file.
As you may have seen that some of the original julia code was removed currently.
My plan is that:

1. We can add some builtin ViZDoom Environments(Like OpenAI Gym, specified by name)
2. Keep it standalone, and then we can have a general Environmet package to combine all these environments. The core `ReinforcementLearning.jl` only needs to interact that general package. Also it is much simpler for peopel who just want to play around with ViZDoom.

If you agree, I'll add more default scenarios after this PR get merged.
Let me know if you have any concern.

**Comment by jbrea** [comment]
Hi @findmyway 

Awesome work, thanks a lot!

1. I agree, it would be great to have some builtin VizDoom environments.
2. If I understand you correctly you have similar plans as what I did with atari games. I maintain a standalone package [ArcadeLearningEnvironment.jl](https://github.com/jbrea/ArcadeLearningEnvironment.jl) and bind it to the RL package with [RLEnvAtari.jl](https://github.com/JuliaReinforcementLearning/RLEnvAtari.jl). If you agree, I would then call the standalone package VizDoom.jl and the binding package RLEnvVizDoom.jl. What do you think?
3. I tested your PR locally on my Arch Linux machine and on an Ubuntu 18.04 server with julia 0.7. In both cases I did not get any error messages during building but when I try ```using RLEnvVizDoom``` I get many messages like this 
```
WARNING: eval from module Base to ViZDoom:    
Expr(:call, :cconvert, Expr(:::, Expr(:curly, :Type, RLEnvVizDoom.ViZDoom.LabelRef)), Expr(:::, :x, RLEnvVizDoom.ViZDoom.LabelRef)) = Expr(:block, #= Symbol("/root/.julia/packages/CxxWrap/C3YsZ/src/CxxWrap.jl"):291 =#, :x)
  ** incremental compilation may be broken for this module **
```
Any ideas?

**Comment by findmyway** [comment]
2. Exactly what I mean. (So I'll continue writing some wrappers and once you have created ViZDoom.jl repo, I'll move the core part there ;)
3. I think those WARNING are caused by the new `@wrapmodule` in [CxxWrap](https://github.com/JuliaInterop/CxxWrap.jl#breaking-changes-for-07). It shouldn't be a big problem.

Also note that since I removed the `__precompile__(false)` by accident. null function error will occur. I'll fix it soon.

**Comment by jbrea** [comment]
Great! ```__precompile__(false)``` solved all issues. Thanks a lot.
I created the repo [VizDoom.jl](https://github.com/JuliaReinforcementLearning/VizDoom.jl).

**Comment by findmyway** [comment]
Ah, the newly created repo is empty. I can't even fork or make a PR...

**Comment by jbrea** [comment]
Uh, sorry. Should be fixed now.

**Comment by findmyway** [comment]
Closed this PR.

After the PR in ViZDoom.jl get merged. I'll make another PR to support the general operations.

**Pull request closed without merging**
